@echo off
cd /d "c:\Users\User\Downloads\architecture-designer-main (1)\architecture-designer-main"
echo Starting Architecture Web App...
echo Opening browser...
start http://localhost:5173
echo Starting server...
call npm run dev
pause
